#### Manipulating Time Series Data in Python

Working with Time Series in Pandas

In [1]:
import pandas as pd
from datetime import datetime

In [2]:
ts = pd.Timestamp("2026-08-26")
print(ts)

2026-08-26 00:00:00

In [3]:
ts = pd.Timestamp(datetime(2026, 8, 26))
print(ts)

2026-08-26 00:00:00

Accessing its components

In [4]:
print(ts.year)
print(ts.month)
print(ts.day)
print(ts.hour)
print(ts.minute)
print(ts.day_name())

2026
8
26
0
0
Wednesday

Timestamp - Period

In [5]:
# entire month of January 2017
pd.Period("2017-01", "M")

Period('2017-01', 'M')

In [9]:
print(pd.Period("2017", "Y"))
print(pd.Period("2017-01", "M"))
print(pd.Period("2017-01-01", "D"))

2017
2017-01
2017-01-01

Frequency

| Frequency   | Meaning      |
| ----------- | ------------ |
| `D`         | Day          |
| `W`         | Week         |
| `M`         | Month        |
| `Q`         | Quarter      |
| `Y`         | Year         |
| `H`         | Hour         |
| `T` / `min` | Minute       |
| `S`         | Second       |
| `B`         | Business day |

In [10]:
print(pd.Period("2017-01", freq="M"))

2017-01

Date Arithmetic

In [11]:
p = pd.Period("2017-01", freq="M")
print(p + 1)

2017-02

Converting Between Frequencies

In [13]:
p = pd.Period("2017-01", freq="M")
p.asfreq("D") # by default, goes to the end of the month

Period('2017-01-31', 'D')

In [14]:
p.asfreq("D", how="start")

Period('2017-01-01', 'D')

Timestamp to Period

In [15]:
p = pd.Timestamp("2017-01-01")
p.to_period(freq="M")

Period('2017-01', 'M')

Period to Timestamp

In [17]:
p = pd.Period("2017-01", freq="M")
print(p.to_timestamp()) # timestamp corresponding to the start of the period
print(p.to_timestamp(how="end")) # timestamp corresponding to the end of the period

2017-01-01 00:00:00
2017-01-31 23:59:59.999999999

Creating a Range of dates

In [18]:
pd.date_range(
    start="2017-01-01",
    end="2017-01-05"
)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05'],
              dtype='datetime64[ns]', freq='D')

In [19]:
pd.date_range(start="2017-01-01", periods=5)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05'],
              dtype='datetime64[ns]', freq='D')

In [20]:
# change the frequency of date range
pd.date_range(start="2017-01-01", periods=5, freq="M")

C:\Users\Senthil\AppData\Local\Temp\ipykernel_9520\1840390302.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  pd.date_range(start="2017-01-01", periods=5, freq="M")

DatetimeIndex(['2017-01-31', '2017-02-28', '2017-03-31', '2017-04-30',
               '2017-05-31'],
              dtype='datetime64[ns]', freq='ME')

Dates as DataFrame Index

In [26]:
dates = pd.date_range(
    start="2017-01-01",
    periods=12
)

df = pd.DataFrame({
        "values" : range(0, 12)
    }, 
    index=dates
)

display(df)

            values
2017-01-01       0
2017-01-02       1
2017-01-03       2
2017-01-04       3
2017-01-05       4
2017-01-06       5
2017-01-07       6
2017-01-08       7
2017-01-09       8
2017-01-10       9
2017-01-11      10
2017-01-12      11

In [24]:
import numpy as np
range(0, 12)

range(0, 12)

In [38]:
df = pd.DataFrame({
    "dates" : ["Jan 1, 2020", "Jan 2, 2020", "Jan 3, 2020"],
    "temperature" : [10, 20, 30]
})

In [39]:
df["dates"] = pd.to_datetime(df["dates"])

In [40]:
display(df)

       dates  temperature
0 2020-01-01           10
1 2020-01-02           20
2 2020-01-03           30

If Date is just an ordinary column, pandas doesn't automatically treat the DataFrame as a time series - so it must be an index

In [41]:
df = df.set_index("dates")
display(df)

            temperature
dates
2020-01-01           10
2020-01-02           20
2020-01-03           30

In [43]:
df.loc["2020-01-01"]

temperature    10
Name: 2020-01-01 00:00:00, dtype: int64